### ISSUE TITLE
Socket.io-client error + undefined filename

### ISSUE THREAD

**Issue by hhumphrey-dazn** [hypery2k/tvml-kit-livereload#8]
I'm coming across a couple of issues and just wanted to check before opening a PR. First when I run this within my tvml project I get 

`TypeError: undefined is not an object (evaluating 'Object.prototype')`

This seems to stem from socket.io-client v1.4+:

https://github.com/socketio/socket.io/issues/2381

Reverting back to 1.3.7 fixes the issue. 

Also filename is missing from the method readFileContent, easily fixable and I'm happy to open a new PR if preferred.

**Comment by hypery2k** [comment]
would be great if you fill a PR as I'm currently busy with other stuff

**Comment by hypery2k** [comment]
I've published version 0.3.0

**Comment by hhumphrey-dazn** [comment]
Thank you! This didn't include #7 any particular reason why?

**Comment by hypery2k** [comment]
sorry my fault. Will fix this
